apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tkbk-demo 
  namespace:  
spec:
  schedule: "* */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tkbk-demo 
            image: 10.254.0.50:5000/tkbk-demo:v1 
            imagePullPolicy: Always
            command:
              - /bin/sh
              - -c
              - make chk1; make chk2 
          restartPolicy: OnFailure
